version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    aws_auth:
      aws_access_key_id: $AWS_ACCESS_KEY_ID
      aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build containers and push to ECR
          command: |
            sudo apt install -y python3-pip
            sudo pip3 install --upgrade awscli
            docker-compose -f docker/docker-compose-dev.yml build
            docker tag docker_supplier_lister-web:latest 850117686356.dkr.ecr.us-east-2.amazonaws.com/test-aws:latest
            eval $(aws ecr get-login --region us-east-2 --no-include-email)
            docker push 850117686356.dkr.ecr.us-east-2.amazonaws.com/personal-redis