version: '2.1'
services:
  web-sandbox:
    container_name: web-sandbox
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../app:/app
    env_file:
      - .env-dev
    ports:
      - "8100:80"
    restart: always
    depends_on:
      mysql-sandbox:
        condition: service_healthy
    links:
      - mysql-sandbox
  mysql-sandbox:
    container_name: mysql-sandbox
    image: mysql:5.7
    ports:
      - "33306:3306"
    env_file:
      - .env-dev
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  faker-sandbox:
    container_name: faker-sandbox
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../faker:/app
    ports:
      - "8101:80"
    restart: always
    depends_on:
      mysql-sandbox:
        condition: service_healthy
    links:
      - mysql-sandbox